/* Presenter notes for the Claude Coaching discovery deck.
   Loaded ONLY when the deck URL carries ?present — this file is never
   referenced from index.html source, so the public deck cannot leak it. */
window.DECK_NOTES = {
  "Welcome": '<span class=\'say\'>&ldquo;Hey <em>[name]</em>, great to meet you! Quick housekeeping first: <em>I record my calls with an AI notetaker so I can focus on you instead of scribbling &mdash; it stays private between us. That okay?</em>&rdquo;</span><span class=\'say\'>&ldquo;Here&rsquo;s how I run these fifteen minutes: first I want to understand what&rsquo;s eating your week, then I&rsquo;ll tell you exactly what I&rsquo;d set up for you, and we&rsquo;ll see if it&rsquo;s a fit. <em>And if it&rsquo;s not a fit, I&rsquo;ll tell you that too.</em>&rdquo;</span><span class=\'warn\'>&#9888; If they say no to recording: stop Otter, continue normally.</span><span class=\'warn\'>&rarr; Then press B to blank the screen. Minutes 1&ndash;4 are LISTENING. Three questions, then stop asking.</span>',
  "The gap": '<span class=\'say\'>Use this ONLY after you&rsquo;ve heard their three answers. It reframes their experience &mdash; it doesn&rsquo;t criticize them.</span><span class=\'say\'>&ldquo;Almost everyone I talk to tried it, asked it a few things, got generic answers back, and quietly decided it was overhyped. <em>That&rsquo;s not you being wrong &mdash; that&rsquo;s the demo.</em> The difference is about ninety minutes of setup nobody walks you through.&rdquo;</span><span class=\'warn\'>&rarr; Their &#9733; answer &mdash; the one task they&rsquo;d hand to an assistant &mdash; goes in the blank card on the next screen. Use their exact words.</span>',
  "Your 90 minutes": '<span class=\'say\'>&ldquo;Here&rsquo;s exactly what your ninety minutes looks like. We get on a call, <em>you drive, I guide every click</em> &mdash; I never touch your accounts or see a password.&rdquo;</span><span class=\'say\'>Point at card 03 and say THEIR answer out loud, in their words: &ldquo;&hellip;and then we automate <em>[their &#9733; answer]</em> &mdash; live, while you watch, before we hang up.&rdquo;</span><span class=\'warn\'>&#9888; One mini-demo MAX, 90 seconds. No demo is fine &mdash; the picture in their head beats pixels.</span>',
  "Monday morning": '<span class=\'say\'>This is the emotional payload. Slow down here.</span><span class=\'say\'>&ldquo;Monday morning after your session, you open your laptop and there&rsquo;s a briefing waiting: your week, your follow-ups, what&rsquo;s overdue, your top three priorities. <em>That&rsquo;s not the future &mdash; that&rsquo;s the Tuesday after we meet.</em>&rdquo;</span><span class=\'warn\'>&rarr; Then press B and run the fit check by voice: Google or Microsoft? &nbsp;Claude account yet? &nbsp;Laptop for the session? &nbsp;Comfort 1&ndash;10 (&ldquo;I guide every click&rdquo;).</span>',
  "The offer": '<span class=\'say\'>Answer their questions FIRST, briefly. Then say this unprompted &mdash; don&rsquo;t wait to be asked.</span><span class=\'say\'>&ldquo;So here&rsquo;s the whole program, and there&rsquo;s only one: it&rsquo;s <em>$497 flat</em>. A thirty-minute intake where I learn your business, the ninety-minute session where we build everything I just described, a written guide of every single thing we set up, and thirty days of my AI coach.&rdquo;</span><span class=\'say\'>&ldquo;And it&rsquo;s genuinely risk-free: <em>full refund any time before your session, no questions. And if you finish and don&rsquo;t think it was worth it &mdash; tell me within seven days and I refund all of it.</em> I can offer that because nobody&rsquo;s ever asked.&rdquo;</span><span class=\'warn\'>&#9888; Don&rsquo;t discount. Personal-list contact only: FRIENDS249 &rarr; $249, expires Aug 31.</span>',
  "Your move": '<span class=\'say\'>&ldquo;If you want it, I&rsquo;ll drop the link in the chat right now &mdash; takes two minutes, and the welcome page books your intake call on the spot.&rdquo;</span><span class=\'say\'><em>&rarr; Paste the link into the meeting chat now.</em> If they buy, stay on while they check out.</span><span class=\'say\'>Close either way: &ldquo;This was genuinely good either way. You&rsquo;ll have a short recap from me today with everything we talked about.&rdquo;</span><span class=\'warn\'>&#9888; &ldquo;Let me think about it&rdquo; &rarr; ONE follow-up at 48h. Never a second.<br>&#9888; Privacy worry &rarr; agree first, then avataragency.ai/claudecoaching/your-data/ &mdash; never argue it on the call.</span>',
};
if (typeof window.__deckNotesReady === 'function') window.__deckNotesReady();
